### ISSUE TITLE
2D detector model

### ISSUE THREAD

**Issue by liyuwei-dgene** [microsoft/multiview-human-pose-estimation-pytorch#10]
Hi! Thanks for the great work. 
I would like to test the network on my own images. Is it possible to release your 2D detector model?  

Thanks.

**Comment by CHUNYUWANG** [comment]
This code has both 2D and 3D estimation functionality. But it is dependent on the camera configurations. I would suggest you to read the paper first. https://chunyuwang.netlify.com/img/ICCV_Cross_view_camera_ready.pdf
