### ISSUE TITLE
Question about Human3.6m dataset 

### ISSUE THREAD

**Issue by ahsan3803** [microsoft/multiview-human-pose-estimation-pytorch#12]
Hi, I got H36M dataset from someone and it's in images along with h5 and .mat annotations files. 
Directories = images/s_{:02d}_act_{:02d}_subact_{:02d}_ca_{:02d} 
image_format= s_{:02d}_act_{:02d}_subact_{:02d}_ca_{:02d}_{:06d}.jpg 

I'm unable to generate the annotations files in pickle format using your H36M Toolbox.
Kindly help me in this regard that how we can generate annotations if we already have data in above mentioned format. Thanks

**Comment by qiuzhongwei-USTB** [comment]
> Hi, I got H36M dataset from someone and it's in images along with h5 and .mat annotations files.
> Directories = images/s_{:02d}act{:02d}subact{:02d}ca{:02d}
> image_format= s_{:02d}act{:02d}subact{:02d}ca{:02d}_{:06d}.jpg
> I'm unable to generate the annotations files in pickle format using your H36M Toolbox.
> Kindly help me in this regard that how we can generate annotations if we already have data in above mentioned format. Thanks

hi, can you share the dataset with me？ Thanks

**Comment by CHUNYUWANG** [comment]
@ahsan3803 I don't know the details of your annotation files so I cannot help you directly. My suggestion is that you read the scripts in H36M Toolbox, and modify them for your annotation formats.

**Comment by lan786** [comment]
@qiuzhongwei-USTB  Hi, did you get dataset?

**Comment by Hwang-dae-won** [comment]
> Hi, I got H36M dataset from someone and it's in images along with h5 and .mat annotations files.
> Directories = images/s_{:02d}_act_{:02d}_subact_{:02d}_ca_{:02d}
> image_format= s_{:02d}_act_{:02d}_subact_{:02d}_ca_{:02d}_{:06d}.jpg
> 
> I'm unable to generate the annotations files in pickle format using your H36M Toolbox.
> Kindly help me in this regard that how we can generate annotations if we already have data in above mentioned format. Thanks

Can I get a .mat annotations files file from you?

**Comment by Ferrnya** [comment]
> Hi, I got H36M dataset from someone and it's in images along with h5 and .mat annotations files.
> Directories = images/s_{:02d}_act_{:02d}_subact_{:02d}_ca_{:02d}
> image_format= s_{:02d}_act_{:02d}_subact_{:02d}_ca_{:02d}_{:06d}.jpg
> 
> I'm unable to generate the annotations files in pickle format using your H36M Toolbox.
> Kindly help me in this regard that how we can generate annotations if we already have data in above mentioned format. Thanks

Hi! Can you share the .pkl annotation files? Thanks!!
