### ISSUE TITLE
In the wild dataset

### ISSUE THREAD

**Issue by ogata2606** [microsoft/multiview-human-pose-estimation-pytorch#13]
Thank you for opening the source code!
I want to try 3d pose estimation in the wild video.

Is it possible to try in the wild dataset?

**Comment by CHUNYUWANG** [comment]
For 2D pose estimation part, please refer to section 3.2 in the [paper](https://chunyuwang.netlify.com/img/ICCV_Cross_view_camera_ready.pdf) for possible workaround. For 3D pose estimation part, it can be directly applied to wild dataset as long as the camera parameters are known.

**Comment by ogata2606** [comment]
Thank you reply to my question.

In the paper, it is compared to multiview 3d pose estimation and single view 3d pose estimation.
Is the camera parameter necessary even if we estimate  3d pose estimation from a single view?

**Comment by CHUNYUWANG** [comment]
Yes, the camera parameters are needed even if you use only one camera.

**Comment by ogata2606** [comment]
OK.
Thank you for responding to the question.

I'll close this issue.

**Comment by lan786** [comment]
@ogata2606  Hi, did you run this code? and what's the result (2D and 3D) if you have run.

**Comment by ogata2606** [comment]
@lan786
Yes. I run this code. 
The H36m data set is fine. But, it does not good in my dataset.
I attach 2d pose estimation result with h36m.
![forward](https://user-images.githubusercontent.com/31497284/67662928-b13e1000-f9a7-11e9-8b91-03251a1af4ba.jpg)
