### ISSUE TITLE
Looking for trained model over the repo

### ISSUE THREAD

**Issue by lyshuga** [microsoft/multiview-human-pose-estimation-pytorch#14]
Hi, I was wondering if there was any place where I can obtain trained models. Thank you in advance.

**Comment by CHUNYUWANG** [comment]
@lyshuga Sorry for the very late response. The trained model can be downloaded here https://1drv.ms/u/s!AjX41AtnTHeTiQzL3Nj6KBEm9_kP?e=36PhwU
