### ISSUE TITLE
visualize video 

### ISSUE THREAD

**Issue by wm901115nwpu** [microsoft/multiview-human-pose-estimation-pytorch#15]
How to generate the demo video? Can you offer me the code of visualizing the video?

**Comment by CHUNYUWANG** [comment]
Hi, the demo is made by pyqtgraph. I don't have plans to release the visualization code since I don't own it (another people inside the company wrote it for his own project).

**Comment by wm901115nwpu** [comment]
OK , thank you for answering it.
