### ISSUE TITLE
running estion_cuda

### ISSUE THREAD

**Issue by wm901115nwpu** [microsoft/multiview-human-pose-estimation-pytorch#16]
I can't run the estimate_cuda. Do I need to configure anything else?

**Comment by CHUNYUWANG** [comment]
What is the error message?

**Comment by wm901115nwpu** [comment]
~/anaconda3/bin/python run/pose3d/estimate_cuda.py --cfg experiments-local/mixed/resnet50/256_fusion.yaml
=> creating output/mixed/multiview_pose_resnet_50/256_fusion
=> creating log/mixed/multiview_pose_resnet_50/256_fusion2019-11-14-17-56

And the program is stuck in, in the log folder, I can't get angthing.
Do I need to configure anything else?

**Comment by CHUNYUWANG** [comment]
It is probably in the process of running. You could try to print the MPJPE of each sample at line 114.

**Comment by wm901115nwpu** [comment]
in terminal, I can't print anything
