### ISSUE TITLE
The annotation files of human36m

### ISSUE THREAD

**Issue by banana16314** [microsoft/multiview-human-pose-estimation-pytorch#20]
Hey, Thanks for u sharing!
Is it possible to share the download link of h36m_train.pkl and h36m_validation.pkl file?
i cloned and read the code from https://github.com/CHUNYUWANG/H36M-Toolbox, but i am unable to use this tool, i have got the human36m images and with the annotation file in json format as _Human36M_subject1_camera.json Human36M_subject1_data.json Human36M_subject1_joint_3d.json_
I just need the *.pkl annotation files. 
Thx for your help!

**Comment by CHUNYUWANG** [comment]
Hi @banana16314 

Can you elaborate why you cannot use  https://github.com/CHUNYUWANG/H36M-Toolbox?

I cannot share the files related to the dataset due to the license restriction. But using the above tool should be able to produce the two pkl files you mentioned.

**Comment by dddyyyplus** [comment]
> Hey, Thanks for u sharing! Is it possible to share the download link of h36m_train.pkl and h36m_validation.pkl file? i cloned and read the code from https://github.com/CHUNYUWANG/H36M-Toolbox, but i am unable to use this tool, i have got the human36m images and with the annotation file in json format as _Human36M_subject1_camera.json Human36M_subject1_data.json Human36M_subject1_joint_3d.json_ I just need the *.pkl annotation files. Thx for your help!

Hi, can you tell me how to get Human36M_subject1_joint_3d.json?
Thank you very much!
