### ISSUE TITLE
Missing pretrained model "mobilenet_v2.pth.tar"

### ISSUE THREAD

**Issue by Shine41** [microsoft/multiview-human-pose-estimation-pytorch#24]
"mobilenet_v2.pth.tar" seems to be missing in the provided link: 

[https://onedrive.live.com/?authkey=%21AF9rKCBVlJ3Qzo8&id=93774C670BD4F835%21930&cid=93774C670BD4F835
](url)

Could you re-upload it? Thanks a lot.

**Comment by CHUNYUWANG** [comment]
Hi,

You can download the pre-trained model here
https://download.pytorch.org/models/mobilenet_v2-b0353104.pth
