### ISSUE TITLE
Missing model_best.pth.tar???

### ISSUE THREAD

**Issue by ChenConnie** [microsoft/multiview-human-pose-estimation-pytorch#28]
hello, when I run this command: python run/pose2d/valid.py --cfg experiments-local/mixed/resnet50/256_fusion.yaml
I meet this error : FileNotFoundError: No such file ro directory, 'output/mixed/multiview_pose_resnet_50/256_fusion/model_best.pth.tar.
could you tell me why? Thank you very much.

**Comment by CHUNYUWANG** [comment]
You can download the model for **resnet152/320_fusion.yaml** [here](https://microsoft-my.sharepoint.com/:u:/p/chnuwa/ESJndFJNYNtAo7KoXUAlRX4BQjH5ticOWj9U6rpVTQhc5g?e=bIiIy1)

**Comment by rhljajodia** [comment]
Hello,
The download link seems invalid. It appears to be visible to a closed group of people so anonymous download is not possible.
Any chance of fixing this? I have the same error.

**Comment by ChenConnie** [comment]
you can download by the link : https://drive.google.com/file/d/1TsjMOXUEZc-goGRqdS891ZgzltDR9_Yc/view?usp=sharing













At 2020-10-05 00:45:52, "rhljajodia" <notifications@github.com> wrote:

Hello,
The download link seems invalid. It appears to be visible to a closed group of people so anonymous download is not possible.
Any chance of fixing this? I have the same error.

**Comment by sklf** [comment]
> you can download by the link : https://drive.google.com/file/d/1TsjMOXUEZc-goGRqdS891ZgzltDR9_Yc/view?usp=sharing At 2020-10-05 00:45:52, "rhljajodia" <notifications@github.com> wrote: Hello, The download link seems invalid. It appears to be visible to a closed group of people so anonymous download is not possible. Any chance of fixing this? I have the same error. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Hi，I downloaded the file. But it seems to be corrupted and I cannot unzip it. Could you please check the file?

**Comment by sklf** [comment]
> Hello,
> The download link seems invalid. It appears to be visible to a closed group of people so anonymous download is not possible.
> Any chance of fixing this? I have the same error.
> 
> @ChenConnie have you managed to fix this? any chance you could help me?

Did you download the file in the new link?  Is it normal? I can't unzip it.

**Comment by PGogo** [comment]
> you can download by the link : https://drive.google.com/file/d/1TsjMOXUEZc-goGRqdS891ZgzltDR9_Yc/view?usp=sharing At 2020-10-05 00:45:52, "rhljajodia" <notifications@github.com> wrote: Hello, The download link seems invalid. It appears to be visible to a closed group of people so anonymous download is not possible. Any chance of fixing this? I have the same error. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

This link also seems to be invalid, can you please provide another one? Thanks!
