### ISSUE TITLE
Quetestions about the organization of H36M image data

### ISSUE THREAD

**Issue by ROC-Zerui** [microsoft/multiview-human-pose-estimation-pytorch#3]
Hi Chunyu,

A great work! Thank you for releasing the code! 

I meet a small problem when I organize the H36M image data. After I download and process the data from (https://github.com/anibali/h36m-fetch),  the image data is organized as: 
```
${POSE_ROOT}
|-- data
`-- |-- h36m
    `-- |-- annot
        |   |-- h36m_train.pkl
        |   |-- h36m_validation.pkl
        `-- images.zip
            `-- images
                |-- S1
                    |-- Directions-1
                        |-- imageSequence
                            |--54138969
                            |--55011271
                            |--58860488
                            |--60457274
                        |-- annot.h5
                    |-- Directions-2
                |-- S11
```
As you see, it is inconsistent with the description in the 'INSTALL.md '. Do you have another processing script ？ If you have, can you share it?

**Comment by CHUNYUWANG** [comment]
Please check this repo to get the "images" and "annot" files: https://github.com/CHUNYUWANG/H36M-Toolbox

**Comment by ROC-Zerui** [comment]
Yeh, I just see it. Thank you for releasing the HM36M-toolbox!!! I will have a try immediately.

**Comment by haohuazhu** [comment]
excuse,could u send the Human3.6M dataset to me please? I register it for a few days,but no reply.If u could,send it to my e-mail:zhuhaohua96@gmail.com. Thanks a lot!Have a nice day!
