### ISSUE TITLE
Limb Length Prior download link broken

### ISSUE THREAD

**Issue by rhljajodia** [microsoft/multiview-human-pose-estimation-pytorch#33]
Hello.
Could you please update the limb-length priors download link :) 
Both the link in the repository and under #6  take me a login page. Please help.
Thank you.

**Comment by CHUNYUWANG** [comment]
Can you take a look at the following link:
https://1drv.ms/u/s!AjX41AtnTHeTiQqGeDYkriGPZ04o?e=ZZcH9H

**Comment by rhljajodia** [comment]
Hello,
This link works perfectly.
Thank you

**Comment by jackspp** [comment]
> Can you take a look at the following link:
> https://1drv.ms/u/s!AjX41AtnTHeTiQqGeDYkriGPZ04o?e=ZZcH9H

Hello.
This link seems broken too. Could you share a new one please?
Thanks a lot.
