### ISSUE TITLE
The link of onedrive broken.

### ISSUE THREAD

**Issue by lecchon** [microsoft/multiview-human-pose-estimation-pytorch#38]
Hello, I found that onedrive links broken when I try to download the limb length prior data (as well as that for mpii), could you please update them?
Thank you!

**Comment by CHUNYUWANG** [comment]
Can you download it using this link?

https://1drv.ms/u/s!AjX41AtnTHeTiQs7hDJ2sYoGJDEB?e=YyJcI4

**Comment by lecchon** [comment]
> Can you download it using this link?
> 
> https://1drv.ms/u/s!AjX41AtnTHeTiQs7hDJ2sYoGJDEB?e=YyJcI4

It seems to be an issue with my network environment instead the links, I will close this issue.
Thank you very much.
