### ISSUE TITLE
Questions for processing the total capture dataset

### ISSUE THREAD

**Issue by ROC-Zerui** [microsoft/multiview-human-pose-estimation-pytorch#5]
Hi Chunyu,

Thanks for releasing the H36M toolbox!
Acutally, I note that you train your models on the Total Capture dataset and few works have done experiments on it. For a fair comparison for future works, can you share how to process the total capture dataset?

Thanks.

**Comment by CHUNYUWANG** [comment]
We will release the code in the future (probably after the CVPR deadline).

**Comment by ROC-Zerui** [comment]
Thank you.

**Comment by CHUNYUWANG** [comment]
Hi, @ROC-Zerui 

Apologies for the delay. We released the toolbox at https://github.com/zhezh/TotalCapture-Toolbox
