### ISSUE TITLE
Unable to download limb length prior from Baidu

### ISSUE THREAD

**Issue by priya-dwivedi** [microsoft/multiview-human-pose-estimation-pytorch#6]
Hello, Fantastic work and I am really interested in testing this out for a use case. But I am unable to download the limb length prior file from Baidu - https://pan.baidu.com/s/1xW4pOdpCeysdvbK33d5YrA

I am able to access the One Drive Link. Is it possible to put this file on One Drive as well?

Thanks!

**Comment by CHUNYUWANG** [comment]
Hi, I uploaded the data to OneDrive. You can download it from the following link:
https://1drv.ms/u/s!AjX41AtnTHeTiQt7xLFmMLrcBuYq?e=KSia8L

**Comment by rhljajodia** [comment]
Hello @priya-dwivedi ,
Any chance you could share the file with me if you still have it? The download links seem broken and I am a little pressed for time. Please help.
