### ISSUE TITLE
the training time seems not to be shown in your paper

### ISSUE THREAD

**Issue by yuzhenbo** [microsoft/multiview-human-pose-estimation-pytorch#7]
Hi, the training time of this method is not descripted clearly in this paper. Can you tell me how long you train 2D or 3D pose estimation in human3.6 and MPII without fusion( just 3D estimation from single image). Thank you very much.

**Comment by CHUNYUWANG** [comment]
The training time for 2D pose estimation varies from one day to one week depending on input image size, backbone networks and GPU cards. The 3D pose estimation does not need training. Generally it can process several frames per second (the reported speed in the paper is several seconds per frame but we significantly improved the speed later).
