### ISSUE TITLE
Question about live Cameras

### ISSUE THREAD

**Issue by ahsan3803** [microsoft/multiview-human-pose-estimation-pytorch#8]
Hi dear Chunyu Wang, thanks for your such a nice work. I want to know that this work can be implemented for live cameras instead of images? I want to use 2 live cameras. Is it possible in your work? I read your work but still I'm confused about my problem.

**Comment by CHUNYUWANG** [comment]
The speed may be an issue when it is used for real time pose processing from live cameras.

**Comment by ahsan3803** [comment]
Yeah I'm already thinking about it but main problem is that how to calibrate cameras within your repository? For cameras calibration we need another method which can be embedded in your repository later or we can calibrate cameras directly in your repository? I'm unable to find any piece of code which can handle live camera calibration that's why I'm asking this question.

**Comment by CHUNYUWANG** [comment]
It does not have the code for camera calibration. We assume the camera parameters are already known as is the case for the benchmark datasets.

**Comment by ahsan3803** [comment]
Yeah but for real-time processing scenario will be different. Thanks for your replies.

**Comment by KungZell** [comment]
> Hi dear Chunyu Wang, thanks for your such a nice work. I want to know that this work can be implemented for live cameras instead of images? I want to use 2 live cameras. Is it possible in your work? I read your work but still I'm confused about my problem.
Hello, dear Lisa, Recently I wanted to realize real-time 3D tracking through two cameras. When browsing GitHub, I found that you are the pioneer in this field. Could you please give me some suggestions in this field ? Thank you very much.

**Comment by KungZell** [comment]
> Yeah but for real-time processing scenario will be different. Thanks for your replies.

Hello, dear Lisa, Recently I wanted to realize real-time 3D tracking through two cameras. When browsing GitHub, I found that you are the pioneer in this field. Could you please give me some suggestions ? Thank you very much.
