### ISSUE TITLE
Question about camera calibration

### ISSUE THREAD

**Issue by schmidje** [microsoft/multiview-human-pose-estimation-pytorch#9]
Hi,

It is unclear to me if you somehow provided camera calibration information to your detection network. If yes, how could I provide my own camera calibration information to use your code with my own images acquired from multiple cameras?

Thank you very much!

Best regards

**Comment by CHUNYUWANG** [comment]
We learn a dedicated model for a particular configuration of cameras. It needs retraining if a new set of cameras is provided. Please see our paper (section 3.2) for more details https://chunyuwang.netlify.com/img/ICCV_Cross_view_camera_ready.pdf

**Comment by lan786** [comment]
@schmidje  Hi, did you run this code? and what's the result (2D and 3D) if you have run.

**Comment by schmidje** [comment]
@lan786 nope, given retraining will require building a training dataset with my camera config which is too much work to do :-/ and not convenient in my opinion. So while I am very interested in this work it is currently not my priority. Sorry!
